[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
